#ifndef LEXER_H
#define LEXER_H

typedef enum {
    TOK_EOF, TOK_INT, TOK_IDENT, TOK_STR, TOK_TRUE, TOK_FALSE,
    TOK_FN, TOK_LET, TOK_IF, TOK_ELSE, TOK_WHILE, TOK_FOR, TOK_IN, TOK_DOTDOT, TOK_RETURN,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE, TOK_LBRACKET, TOK_RBRACKET,
    TOK_COMMA, TOK_COLON, TOK_COLONCOLON, TOK_SEMI, TOK_ASSIGN, TOK_PLUS, TOK_MINUS, TOK_STAR,
    TOK_SLASH, TOK_PERCENT, TOK_EQ, TOK_NE, TOK_LT, TOK_GT, TOK_LE, TOK_GE,
    TOK_AND, TOK_OR, TOK_NOT, TOK_PRINT, TOK_LEN, TOK_PUSH, TOK_HINT,
    TOK_TYPE, TOK_AT, TOK_PIPE, TOK_MATCH, TOK_ARROW, TOK_FATARROW, TOK_ENUM,
    TOK_TILDE, TOK_BANG, TOK_QMARK, TOK_UNLESS, TOK_FOREVER, TOK_BREAK,
    TOK_CONTINUE, TOK_ASSERT, TOK_DEFER, TOK_GUARD, TOK_UNTIL, TOK_SWAP,
    TOK_DOTDOTDOT,
    TOK_PLUSEQ, TOK_MINUSEQ, TOK_STAREQ, TOK_SLASHEQ, TOK_PERCENTEQ,
    TOK_STEP, TOK_TRY, TOK_RESCUE, TOK_RAISE, TOK_WHERE, TOK_WHEN,
    TOK_ONCE, TOK_MAYBE
} TokenType;

typedef struct {
    TokenType type;
    char *value;
    int int_val;
    int line;
} Token;

typedef struct {
    char *src;
    int pos;
    int line;
} Lexer;

Lexer *lexer_new(char *src);
Token lexer_next(Lexer *lex);
void lexer_free(Lexer *lex);

#endif
